---
- name: set up unattended upgrades and email

  apt:
    name:
      - unattended-upgrades
      - apt-listchanges
      - needrestart
      - mailutils
      - needrestart
      - default-dbus-session-bus
      - python3-apt-dbg
      - python3-dbus-dbg
      - eximon4
      - swaks
      - dns-root-data
