---
- name: Set up host for nebensinn site
  hosts: site

  tasks:
    - name: install packages for unattended upgrades and email
      apt:
        name:
          - unattended-upgrades
          - apt-listchanges
          - needrestart
          - mailutils
          - default-dbus-session-bus
          - python3-apt-dbg
          - python3-dbus-dbg
          - eximon4
          - swaks
          - dns-root-data
          - file

    - pause:
        prompt: Please run dpkg-reconfigure exim4-config on the host now

    - pause:
        prompt: Please provide SMTP login data in passwd.client in form *:username:password

    - name: copy user credentials
      copy:
        src: passwd.client
        dest: /etc/exim4

    - name: copy exim variables
      copy:
        src: exim4.conf.localmacros
        dest: /etc/exim4

    - name: allow unqualified domains (e.g. email to root)
      block:
      - lineinfile:
          dest: "/etc/exim4/conf.d/main/02_exim4-config_options"
          regexp: "^#? sender_unqualified_hosts ="
          line: " sender_unqualified_hosts = *"
        notify: restart exim
      - lineinfile:
          dest: "/etc/exim4/conf.d/main/02_exim4-config_options"
          regexp: "^#? recipient_unqualified_hosts ="
          line: " recipient_unqualified_hosts = *"
        notify: restart exim

    - name: ensure exim4 is reloaded if need be
      meta: flush_handlers

    - name: send test email
      mail:
        subject: Test email from Ansible

    - pause:
        prompt: Please check if the test email arrived.

  handlers:
    - name: update exim configuration
      command: update-exim4.conf
      listen: "restart exim"
    - name: restart exim server
      systemd:
        name: exim4
        state: restarted
      listen: "restart exim"
