#!/usr/bin/env ansible-playbook
---
- import_playbook: playbooks/10_ssh.yml
- import_playbook: playbooks/15_ssl.yml
- import_playbook: playbooks/19_static_page.yml
- import_playbook: playbooks/20_webserver.yml
- import_playbook: playbooks/30_services.yml
- import_playbook: playbooks/40_ghost_restore.yml
- import_playbook: playbooks/45_ghost_backup.yml
