---
- name: Set up services for nebensinn site
  hosts: site
  vars_prompt:
    - name: postfix_relayhost_user
      prompt: "Email user name?"
      private: no

    - name: postfix_relayhost_pass
      prompt: "Email password?"

  gather_facts: no
  roles:
  - role: ansible-change-ssh-port
  - role: ansible-role-postfix
    postfix_domain: 'nebensinn.com'
    postfix_notify_email: 'webmaster@nebensinn.com'
    postfix_relay_server: 'smtp.ionos.de'
    postfix_use_smtp: true
    postfix_smtp_sasl_password_maps: 'hash:/etc/postfix/sasl_passwd'
  - role: geerlingguy.postfix
  - role: jnv.unattended-upgrades
    unattended_origins_patterns:
    - 'origin=Debian,codename=${distro_codename}-updates'
    - 'origin=Debian,codename=${distro_codename},label=Debian'
    - 'origin=Debian,codename=${distro_codename},label=Debian-Security'
    unattended_mail: 'webmaster@nebensinn.com'
    unattended_remove_unused_dependencies: true
    unattended_automatic_reboot: true
    unattended_automatic_reboot_time: '03:00'
