---
- name: Set up web server
  hosts: site
  roles:
  - role: geerlingguy.nginx
    nginx_client_max_body_size: "10m"
    nginx_remove_default_vhost: true
    nginx_vhosts:
    - listen: "80"
      server_name: "{{ansible_host}} www.{{ansible_host}}"
      return: "301 https://{{ansible_host}}$request_uri"
      filename: "{{ansible_host}}.80.conf"
    - listen: "443 ssl http2"
      server_name: "{{ansible_host}} www.{{ansible_host}}"
      root: "/var/www/static_html"
      index: "index.html index.htm"
      state: "present"
      template: "{{ nginx_vhost_template }}"
      filename: "{{ansible_host}}.443.conf"
      extra_parameters: |
        ssl_certificate     /etc/letsencrypt/live/{{ansible_host}}/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/{{ansible_host}}/privkey.pem;
        # recommended settings from https://cipherli.st/
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;
        ssl_dhparam /etc/ssl/certs/dhparam.pem;
        ssl_ciphers EECDH+AESGCM:EDH+AESGCM;
        ssl_ecdh_curve secp384r1;
        ssl_session_timeout  10m;
        ssl_session_cache shared:SSL:10m;
        ssl_session_tickets off;
        ssl_stapling on;
        ssl_stapling_verify on;
        add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload";
        add_header X-Frame-Options DENY;
        add_header X-Content-Type-Options nosniff;
        add_header X-XSS-Protection "1; mode=block";
        # proxy to Ghost blog
        location /bookclub {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $http_host;
            proxy_pass http://127.0.0.1:2368;
        }
        # error pages
        error_page 301 /301.html;
        error_page 404 /404.html;
        error_page 502 /502.html;
  - role: geerlingguy.certbot
    certbot_create_if_missing: true
    certbot_create_method: standalone
    certbot_admin_email: webmaster@{{ansible_host}}
    certbot_certs:
    - domains:
        - '{{ansible_host}}'
        - 'www.{{ansible_host}}'
    certbot_create_standalone_stop_services:
    - nginx
