---
- name: Set up services
  hosts: site
  vars_prompt:
    - name: exim4_client_user
      prompt: "Email user name?"
      private: no

    - name: exim4_client_password
      prompt: "Email password?"

    - name: exim4_target_address
      prompt: "Target email address?"
      private: no
  roles:
  - role: jnv.unattended-upgrades
    unattended_origins_patterns:
    - 'origin=Debian,codename=${distro_codename}-updates'
    - 'origin=Debian,codename=${distro_codename},label=Debian'
    - 'origin=Debian,codename=${distro_codename},label=Debian-Security'
    - 'origin=Node Source,codename=${distro_codename},label=Node Source'
    unattended_mail: 'webmaster@{{ansible_host}}'
    unattended_remove_unused_dependencies: true
    unattended_automatic_reboot: true
    unattended_automatic_reboot_time: '03:00'
  - role: adegtyarev.ansible_role_exim4
    exim4_dc_eximconfig_configtype: satellite
    exim4_dc_readhost: "{{ansible_host}}"
    exim4_dc_smarthost: smtp.ionos.de::587
    exim4_dc_hide_mailname: false
    exim4_features_enable:
      - name: 02_exim4-custom_options
        group: main
    exim4_custom_options:
      sender_unqualified_hosts: "*"
      recipient_unqualified_hosts: "*"
    exim4_passwd_client:
    - '*:{{exim4_client_user}}:{{exim4_client_password}}'
  tasks:
  - name: add root alias
    lineinfile:
      dest: "/etc/aliases"
      regexp: "^root:.*$"
      line: "root: {{exim4_target_address}}"
  - name: ensure exim is reloaded if need be
    meta: flush_handlers
  - name: send test email
    mail:
      subject: Test email from Ansible
