---
- name: Restore Ghost blog
  hosts: site
  roles:
  - role: ansible-role-ghost-restore
  aws_s3_bucket_name: ""
  aws_access_key: ""
  aws_secret_key: ""
  tasks:
  # TODO install systemd unit for Ghost
  - name: set up Ghost back up Cron job
    # TODO
    # - download repo ansible-role-ghost-backup
    # - set up virtualenv
    # - pip install ansible
    # - copy ansible script
    # - copy cron script
  - name: test Ghost back up Cron job
    # TODO
    # - run cron script
    # - check AWS S3 change time stamp
