---
- name: Restore Ghost blog
  hosts: site
  vars_prompt:
    - name: local_aws_s3_bucket_name
      prompt: "S3 bucket name?"
      private: no

    - name: local_aws_access_key
      prompt: "AWS Access Key?"
      private: no

    - name: local_aws_secret_key
      prompt: "AWS Secret Access Key?"
  roles:
  - role: geerlingguy.nodejs
    nodejs_version: "12.x"
    nodejs_npm_global_packages:
    - name: ghost-cli
  - role: ansible-role-ghost-restore
    aws_s3_bucket_name: "{{local_aws_s3_bucket_name}}"
    aws_access_key: "{{local_aws_access_key}}"
    aws_secret_key: "{{local_aws_secret_key}}"
  #tasks:
  ## TODO
  ## - install systemd unit for Ghost
  ## - install cron hourly script for availability check
  #- name: set up Ghost back up Cron job
  #  # TODO
  #  # - download repo ansible-role-ghost-backup
  #  # - set up virtualenv
  #  # - pip install ansible
  #  # - copy ansible script
  #  # - copy cron script
  #- name: test Ghost back up Cron job
  #  # TODO
  #  # - run cron script
  #  # - check AWS S3 change time stamp
